title: John Doe # your name (or website title) here
logo: "/images/avatar.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Matthew J Barnhart 
  <br><br>
  Mastering Engineer based in Chicago, Ill. 
  <br><br>
  <a href="https://www.chicagomasteringservice.com/">Chicago Mastering Service</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
